### ISSUE TITLE
Menu icons massive in Ubuntu

### ISSUE THREAD

**Issue by BoatsAreRockable** [BoatsAreRockable/animator#68]
![issue](http://s10.postimg.org/fxwfo8w5l/BA_ubuntu_menu_issue.png)

Ran the source in an Ubuntu virtual machine to see how BA appeared. For reason the menu icons appear full size rather than resizing like they do in Windows. The current menu icons need changing to match the FontAwesome ones anyway.

I guess the solution would be for small icons that aren't resized to be displayed for Linux users.

**Comment by le717** [comment]
I think I should take this chance and advocate _removing_ the menu icons altogether. Hear me out on this one.

Nobody does this. Windows, Mac, or Linux, nobody puts icons in the menu bar. When it is done, that app stands out (not always in a good way) because nobody does that. When it is used and accepted, it is a context everybody understands and makes sense in (like the Favorites menu in your web browser). Go look through your installed applications and see how often native menus
